Add CONFIG_BONDING=y
ni/linux pull request #128
Opened 2023-08-09 08:37 UTC by sqooi-ni

Added CONFIG_BONDING=y to nati_bluefin_defconfig.

2023-08-09 14:10 UTC, bstreiff requested changes
Hi,

1. Please set the base branch for this PR to [`bluefin/master/4.1`](https://github.com/ni/linux/tree/bluefin/master/4.1) instead of the 20.0 release branch.
2. Please rewrite your commit message to fix the Linux kernel commit message standards; you need a subject line and a `Signed-off-by`. [This commit](https://github.com/ni/linux/commit/322f06a5b4ad8cd34c1b945e5c1a62d47a0c684e) is an example of a simple defconfig change like this one.
3. Could you put this between `CONFIG_NETDEVICES=y` and `CONFIG_TUN=y`? That's where it would go in order if we did this via the "typical" `ARCH=arm make nati_bluefin_defconfig && ARCH=arm make menuconfig && ARCH=arm make savedefconfig && cp defconfig arch/arm/configs/nati_bluefin_defconfig` flow. (Unfortunately we weren't strict about doing that in the past, so if you do that now it'll re-sort a bunch of other things that aren't relevant to your change.)

2023-08-10 07:07 UTC, sqooi-ni commented
> 3\. Could you put this between `CONFIG_NETDEVICES=y` and `CONFIG_TUN=y`? That's where it would go in order if we did this via the "typical" `ARCH=arm make nati_bluefin_defconfig && ARCH=arm make menuconfig && ARCH=arm make savedefconfig && cp defconfig arch/arm/configs/nati_bluefin_defconfig` flow. (Unfortunately we weren't strict about doing that in the past, so if you do that now it'll re-sort a bunch of other things that aren't relevant to your change.)

Do I need to run "ARCH=arm make nati_bluefin_defconfig && ARCH=arm make menuconfig && ARCH=arm make savedefconfig && cp defconfig arch/arm/configs/nati_bluefin_defconfig" command at directory "/arch/arm/configs"?

2023-08-11 01:25 UTC, bstreiff commented
> Do I need to run "ARCH=arm make nati_bluefin_defconfig && ARCH=arm make menuconfig && ARCH=arm make savedefconfig && cp defconfig arch/arm/configs/nati_bluefin_defconfig" command at directory "/arch/arm/configs"?

Nope. If you do that now you'll end up with a patch that has a bunch of noise because some other stuff wasn't put in the right places. I'll do a cleanup commit to sort everything all at once, standalone from this PR.

2023-08-11 01:25 UTC, bstreiff approved these changes

2023-08-11 01:25 UTC, merged