nati_x86_64_defconfig: Enable NTFS3 module
ni/linux pull request #163
Opened 2024-06-18 06:11 UTC by terrywu2000

Enable NTFS3 for better performance to read/write NTFS filesystem

2024-06-18 15:47 UTC, chaitu236 requested changes
Changes look ok but commit needs to be signed (i.e., `git commit -s ..`).

Also, commit description needs to follow conventions, e.g., "nati_x86_64_defconfig: Enable NTFS3 module"

2024-06-18 15:57 UTC, gratian commented
Thanks, like @chaitu236 mentioned the changes look good but the commit needs a subject line and "Signed-off-by:" line to conform to kernel commit guidelines. You can see and example here: https://github.com/ni/linux/commit/3494faaf50f25d259b44bb45c2952f8ca246c1bd

Something like:

```
nati_x86_64_defconfig: enable NTFS3 support

Enable NTFS3 module and associated options. This improves
read/write performance on NTFS file systems.

Signed-off-by: Terry Wu <terry.wu@ni.com>
```

2024-06-21 03:11 UTC, terrywu2000 commented
Already updated the message as suggested and pushed the change again.

2024-06-21 03:19 UTC, chaitu236 approved these changes

2024-06-21 12:56 UTC, gratian approved these changes

2024-06-21 12:56 UTC, merged